[package]
name = "expert_system"
version = "0.1.0"
authors = ["Anatoliy Lischynsky <alischyn@student.unit.ua>"]
edition = "2018"

[dependencies]
peg = "^0.6.2"
crossterm = "^0.17.4"
failure = "^0.1.8"
rustyline = "^6.1.2"
